// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: createPost.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
insert into post(title, content, writer_id)VALUES($1, $2, $3) RETURNING id, title, content, post_type, writer_id, created_at, updated_at
`

type CreatePostParams struct {
	Title    string
	Content  sql.NullString
	WriterID uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Title, arg.Content, arg.WriterID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.PostType,
		&i.WriterID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
