// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type User struct {
	ID        string
	Name      string
	Email     string
	Password  string
	UpdatedAt sql.NullTime
	CreatedAt sql.NullTime
}
